name: Publish and deploy

on:
  push: 
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish: 
    if: github.repository == 'teidesu/telegram-oauth' # do not run on forks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/teidesu/telegram-oauth
          tags: type=sha
          flavor: latest=true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
